<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType Condition="'$(OS)' == 'Windows_NT'">WinExe</OutputType>
    <OutputType Condition="'$(OS)' != 'Windows_NT'">Exe</OutputType>
    <TargetFramework Condition="'$(OS)' == 'Windows_NT'">net8.0-windows</TargetFramework>
    <TargetFramework Condition="'$(OS)' != 'Windows_NT'">net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms Condition="'$(OS)' == 'Windows_NT'">true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup Condition="'$(OS)' == 'Windows_NT'">
    <Compile Remove="NonWindowsStub.cs" />
  </ItemGroup>

  <ItemGroup Condition="'$(OS)' != 'Windows_NT'">
    <Compile Remove="MainForm.cs" />
    <Compile Remove="Program.cs" />
  </ItemGroup>

</Project>