<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DesktopComputerUse.Contracts\DesktopComputerUse.Contracts.csproj" />
    <ProjectReference Include="..\DesktopComputerUse.ProfileIntelligence\DesktopComputerUse.ProfileIntelligence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GitHub.Copilot.SDK" Version="1.0.15" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
